// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CarpetaOpcion generated by hbm2java
 */
@Entity
@Table(name = "carpeta_opcion", schema = "seguridad", catalog = "siisspolweb")
public class CarpetaOpcion implements java.io.Serializable {

	private int idCarpetaOpcion;
	private CarpetaOpcion carpetaOpcion;
	private Icono icono;
	private String nombre;
	private String descripcion;
	private int orden;
	private String codigo;
	private Integer nivel;
	private String objeto;
	private String parametro;
	private String tipoAbrir;
	private boolean visible;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<CarpetaOpcion> carpetaOpcions = new HashSet<CarpetaOpcion>(0);
	private Set<Opcion> opcions = new HashSet<Opcion>(0);

	public CarpetaOpcion() {
	}

	public CarpetaOpcion(int idCarpetaOpcion, Icono icono, String nombre, int orden, boolean visible,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idCarpetaOpcion = idCarpetaOpcion;
		this.icono = icono;
		this.nombre = nombre;
		this.orden = orden;
		this.visible = visible;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public CarpetaOpcion(int idCarpetaOpcion, CarpetaOpcion carpetaOpcion, Icono icono, String nombre,
			String descripcion, int orden, String codigo, Integer nivel, String objeto, String parametro,
			String tipoAbrir, boolean visible, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo, Set<CarpetaOpcion> carpetaOpcions,
			Set<Opcion> opcions) {
		this.idCarpetaOpcion = idCarpetaOpcion;
		this.carpetaOpcion = carpetaOpcion;
		this.icono = icono;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.codigo = codigo;
		this.nivel = nivel;
		this.objeto = objeto;
		this.parametro = parametro;
		this.tipoAbrir = tipoAbrir;
		this.visible = visible;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.carpetaOpcions = carpetaOpcions;
		this.opcions = opcions;
	}

	@Id

	@Column(name = "id_carpeta_opcion", unique = true, nullable = false)
	public int getIdCarpetaOpcion() {
		return this.idCarpetaOpcion;
	}

	public void setIdCarpetaOpcion(int idCarpetaOpcion) {
		this.idCarpetaOpcion = idCarpetaOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carpeta_opcion_padre")
	public CarpetaOpcion getCarpetaOpcion() {
		return this.carpetaOpcion;
	}

	public void setCarpetaOpcion(CarpetaOpcion carpetaOpcion) {
		this.carpetaOpcion = carpetaOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_icono", nullable = false)
	public Icono getIcono() {
		return this.icono;
	}

	public void setIcono(Icono icono) {
		this.icono = icono;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "codigo", length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "objeto", length = 100)
	public String getObjeto() {
		return this.objeto;
	}

	public void setObjeto(String objeto) {
		this.objeto = objeto;
	}

	@Column(name = "parametro", length = 100)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	@Column(name = "tipo_abrir", length = 2)
	public String getTipoAbrir() {
		return this.tipoAbrir;
	}

	public void setTipoAbrir(String tipoAbrir) {
		this.tipoAbrir = tipoAbrir;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carpetaOpcion")
	public Set<CarpetaOpcion> getCarpetaOpcions() {
		return this.carpetaOpcions;
	}

	public void setCarpetaOpcions(Set<CarpetaOpcion> carpetaOpcions) {
		this.carpetaOpcions = carpetaOpcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carpetaOpcion")
	public Set<Opcion> getOpcions() {
		return this.opcions;
	}

	public void setOpcions(Set<Opcion> opcions) {
		this.opcions = opcions;
	}

}
