// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlGui generated by hbm2java
 */
@Entity
@Table(name = "control_gui", schema = "comun", catalog = "siisspolweb")
public class ControlGui implements java.io.Serializable {


	@Id
	@Column(name = "id_control_gui", unique = true, nullable = false)
	private int id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_acceso", nullable = false)
	private TipoAcceso tipoAcceso;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_control", nullable = false)
	private TipoControl tipoControl;

	@Column(name = "opcion")
	private Integer opcion;


	@Column(name = "objeto", length = 100)
	private String objeto;

	@Column(name = "control", nullable = false, length = 100)
	private String control;

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	private String creacionUsuario;}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	private Date creacionFecha;

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	private String creacionEquipo;

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	private String modificaUsuario;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	private Date modificaFecha;

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	private String modificaEquipo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "controlGui")
	private Collection<MensajeIdioma> mensajeIdiomas = new ArrayList<>();

	public ControlGui() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TipoAcceso getTipoAcceso() {
		return tipoAcceso;
	}

	public void setTipoAcceso(TipoAcceso tipoAcceso) {
		this.tipoAcceso = tipoAcceso;
	}

	public TipoControl getTipoControl() {
		return tipoControl;
	}

	public void setTipoControl(TipoControl tipoControl) {
		this.tipoControl = tipoControl;
	}

	public Integer getOpcion() {
		return opcion;
	}

	public void setOpcion(Integer opcion) {
		this.opcion = opcion;
	}

	public String getObjeto() {
		return objeto;
	}

	public void setObjeto(String objeto) {
		this.objeto = objeto;
	}

	public String getControl() {
		return control;
	}

	public void setControl(String control) {
		this.control = control;
	}

	public String getCreacionUsuario() {
		return creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	public Date getCreacionFecha() {
		return creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	public String getCreacionEquipo() {
		return creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	public String getModificaUsuario() {
		return modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	public Date getModificaFecha() {
		return modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	public String getModificaEquipo() {
		return modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	public Collection<MensajeIdioma> getMensajeIdiomas() {
		return mensajeIdiomas;
	}

	public void setMensajeIdiomas(Collection<MensajeIdioma> mensajeIdiomas) {
		this.mensajeIdiomas = mensajeIdiomas;
	}
}
