// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DenominacionMonedaId generated by hbm2java
 */
@Embeddable
public class DenominacionMonedaId implements java.io.Serializable {

	private char moneda;
	private int sec;

	public DenominacionMonedaId() {
	}

	public DenominacionMonedaId(char moneda, int sec) {
		this.moneda = moneda;
		this.sec = sec;
	}

	@Column(name = "moneda", nullable = false, length = 1)
	public char getMoneda() {
		return this.moneda;
	}

	public void setMoneda(char moneda) {
		this.moneda = moneda;
	}

	@Column(name = "sec", nullable = false)
	public int getSec() {
		return this.sec;
	}

	public void setSec(int sec) {
		this.sec = sec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DenominacionMonedaId))
			return false;
		DenominacionMonedaId castOther = (DenominacionMonedaId) other;

		return (this.getMoneda() == castOther.getMoneda()) && (this.getSec() == castOther.getSec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMoneda();
		result = 37 * result + this.getSec();
		return result;
	}

}
