// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estacion generated by hbm2java
 */
@Entity
@Table(name = "estacion", schema = "seguridad", catalog = "siisspolweb")
public class Estacion implements java.io.Serializable {

	private int idEstacion;
	private String hostname;
	private String ip;
	private String descripcion;
	private String ubicacion;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<ImpresoraEstacion> impresoraEstacions = new HashSet<ImpresoraEstacion>(0);
	private Set<EstacionUsuario> estacionUsuarios = new HashSet<EstacionUsuario>(0);

	public Estacion() {
	}

	public Estacion(int idEstacion, String hostname, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idEstacion = idEstacion;
		this.hostname = hostname;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Estacion(int idEstacion, String hostname, String ip, String descripcion, String ubicacion,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<ImpresoraEstacion> impresoraEstacions,
			Set<EstacionUsuario> estacionUsuarios) {
		this.idEstacion = idEstacion;
		this.hostname = hostname;
		this.ip = ip;
		this.descripcion = descripcion;
		this.ubicacion = ubicacion;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.impresoraEstacions = impresoraEstacions;
		this.estacionUsuarios = estacionUsuarios;
	}

	@Id

	@Column(name = "id_estacion", unique = true, nullable = false)
	public int getIdEstacion() {
		return this.idEstacion;
	}

	public void setIdEstacion(int idEstacion) {
		this.idEstacion = idEstacion;
	}

	@Column(name = "hostname", nullable = false, length = 50)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "ip", length = 15)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ubicacion", length = 50)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacion")
	public Set<ImpresoraEstacion> getImpresoraEstacions() {
		return this.impresoraEstacions;
	}

	public void setImpresoraEstacions(Set<ImpresoraEstacion> impresoraEstacions) {
		this.impresoraEstacions = impresoraEstacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estacion")
	public Set<EstacionUsuario> getEstacionUsuarios() {
		return this.estacionUsuarios;
	}

	public void setEstacionUsuarios(Set<EstacionUsuario> estacionUsuarios) {
		this.estacionUsuarios = estacionUsuarios;
	}

}
