// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstacionUsuarioId generated by hbm2java
 */
@Embeddable
public class EstacionUsuarioId implements java.io.Serializable {

	private int idEstacion;
	private String idUsuario;

	public EstacionUsuarioId() {
	}

	public EstacionUsuarioId(int idEstacion, String idUsuario) {
		this.idEstacion = idEstacion;
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_estacion", nullable = false)
	public int getIdEstacion() {
		return this.idEstacion;
	}

	public void setIdEstacion(int idEstacion) {
		this.idEstacion = idEstacion;
	}

	@Column(name = "id_usuario", nullable = false, length = 20)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstacionUsuarioId))
			return false;
		EstacionUsuarioId castOther = (EstacionUsuarioId) other;

		return (this.getIdEstacion() == castOther.getIdEstacion())
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEstacion();
		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		return result;
	}

}
