// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstructuraOrganizacional generated by hbm2java
 */
@Entity
@Table(name = "estructura_organizacional", schema = "seguridad", catalog = "siisspolweb")
public class EstructuraOrganizacional implements java.io.Serializable {

	private int idEstructuraOrganizacional;
	private EstructuraOrganizacional estructuraOrganizacional;
	private NivelEstructuraOrg nivelEstructuraOrg;
	private String codigo;
	private String codigoAlterno;
	private String descripcion;
	private int orden;
	private char estado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<EstructuraOrganizacional> estructuraOrganizacionals = new HashSet<EstructuraOrganizacional>(0);

	public EstructuraOrganizacional() {
	}

	public EstructuraOrganizacional(int idEstructuraOrganizacional, NivelEstructuraOrg nivelEstructuraOrg,
			String codigo, String descripcion, int orden, char estado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idEstructuraOrganizacional = idEstructuraOrganizacional;
		this.nivelEstructuraOrg = nivelEstructuraOrg;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.orden = orden;
		this.estado = estado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public EstructuraOrganizacional(int idEstructuraOrganizacional, EstructuraOrganizacional estructuraOrganizacional,
			NivelEstructuraOrg nivelEstructuraOrg, String codigo, String codigoAlterno, String descripcion, int orden,
			char estado, String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<Usuario> usuarios,
			Set<EstructuraOrganizacional> estructuraOrganizacionals) {
		this.idEstructuraOrganizacional = idEstructuraOrganizacional;
		this.estructuraOrganizacional = estructuraOrganizacional;
		this.nivelEstructuraOrg = nivelEstructuraOrg;
		this.codigo = codigo;
		this.codigoAlterno = codigoAlterno;
		this.descripcion = descripcion;
		this.orden = orden;
		this.estado = estado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.usuarios = usuarios;
		this.estructuraOrganizacionals = estructuraOrganizacionals;
	}

	@Id

	@Column(name = "id_estructura_organizacional", unique = true, nullable = false)
	public int getIdEstructuraOrganizacional() {
		return this.idEstructuraOrganizacional;
	}

	public void setIdEstructuraOrganizacional(int idEstructuraOrganizacional) {
		this.idEstructuraOrganizacional = idEstructuraOrganizacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estructura_organizacional_padre")
	public EstructuraOrganizacional getEstructuraOrganizacional() {
		return this.estructuraOrganizacional;
	}

	public void setEstructuraOrganizacional(EstructuraOrganizacional estructuraOrganizacional) {
		this.estructuraOrganizacional = estructuraOrganizacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nivel_estructura_org", nullable = false)
	public NivelEstructuraOrg getNivelEstructuraOrg() {
		return this.nivelEstructuraOrg;
	}

	public void setNivelEstructuraOrg(NivelEstructuraOrg nivelEstructuraOrg) {
		this.nivelEstructuraOrg = nivelEstructuraOrg;
	}

	@Column(name = "codigo", nullable = false, length = 15)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "codigo_alterno", length = 15)
	public String getCodigoAlterno() {
		return this.codigoAlterno;
	}

	public void setCodigoAlterno(String codigoAlterno) {
		this.codigoAlterno = codigoAlterno;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estructuraOrganizacional")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estructuraOrganizacional")
	public Set<EstructuraOrganizacional> getEstructuraOrganizacionals() {
		return this.estructuraOrganizacionals;
	}

	public void setEstructuraOrganizacionals(Set<EstructuraOrganizacional> estructuraOrganizacionals) {
		this.estructuraOrganizacionals = estructuraOrganizacionals;
	}

}
