// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritoId generated by hbm2java
 */
@Embeddable
public class FavoritoId implements java.io.Serializable {

	private String idUsuario;
	private int idOpcion;

	public FavoritoId() {
	}

	public FavoritoId(String idUsuario, int idOpcion) {
		this.idUsuario = idUsuario;
		this.idOpcion = idOpcion;
	}

	@Column(name = "id_usuario", nullable = false, length = 20)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_opcion", nullable = false)
	public int getIdOpcion() {
		return this.idOpcion;
	}

	public void setIdOpcion(int idOpcion) {
		this.idOpcion = idOpcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritoId))
			return false;
		FavoritoId castOther = (FavoritoId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
				&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())))
				&& (this.getIdOpcion() == castOther.getIdOpcion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result + this.getIdOpcion();
		return result;
	}

}
