// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImpresoraEstacionId generated by hbm2java
 */
@Embeddable
public class ImpresoraEstacionId implements java.io.Serializable {

	private int idEstacion;
	private int idImpresora;

	public ImpresoraEstacionId() {
	}

	public ImpresoraEstacionId(int idEstacion, int idImpresora) {
		this.idEstacion = idEstacion;
		this.idImpresora = idImpresora;
	}

	@Column(name = "id_estacion", nullable = false)
	public int getIdEstacion() {
		return this.idEstacion;
	}

	public void setIdEstacion(int idEstacion) {
		this.idEstacion = idEstacion;
	}

	@Column(name = "id_impresora", nullable = false)
	public int getIdImpresora() {
		return this.idImpresora;
	}

	public void setIdImpresora(int idImpresora) {
		this.idImpresora = idImpresora;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImpresoraEstacionId))
			return false;
		ImpresoraEstacionId castOther = (ImpresoraEstacionId) other;

		return (this.getIdEstacion() == castOther.getIdEstacion())
				&& (this.getIdImpresora() == castOther.getIdImpresora());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEstacion();
		result = 37 * result + this.getIdImpresora();
		return result;
	}

}
