// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeIdiomaId generated by hbm2java
 */
@Embeddable
public class MensajeIdiomaId implements java.io.Serializable {

	private int idControlGui;
	private int idIdioma;

	public MensajeIdiomaId() {
	}

	public MensajeIdiomaId(int idControlGui, int idIdioma) {
		this.idControlGui = idControlGui;
		this.idIdioma = idIdioma;
	}

	@Column(name = "id_control_gui", nullable = false)
	public int getIdControlGui() {
		return this.idControlGui;
	}

	public void setIdControlGui(int idControlGui) {
		this.idControlGui = idControlGui;
	}

	@Column(name = "id_idioma", nullable = false)
	public int getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(int idIdioma) {
		this.idIdioma = idIdioma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensajeIdiomaId))
			return false;
		MensajeIdiomaId castOther = (MensajeIdiomaId) other;

		return (this.getIdControlGui() == castOther.getIdControlGui())
				&& (this.getIdIdioma() == castOther.getIdIdioma());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdControlGui();
		result = 37 * result + this.getIdIdioma();
		return result;
	}

}
