// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MotivoCierreSesion generated by hbm2java
 */
@Entity
@Table(name = "motivo_cierre_sesion", schema = "seguridad", catalog = "siisspolweb")
public class MotivoCierreSesion implements java.io.Serializable {

	private int idMotivoCierreSesion;
	private String motivo;
	private boolean vigente;
	private boolean esLunch;
	private boolean esSalidaDefinitiva;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public MotivoCierreSesion() {
	}

	public MotivoCierreSesion(int idMotivoCierreSesion, String motivo, boolean vigente, boolean esLunch,
			boolean esSalidaDefinitiva, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idMotivoCierreSesion = idMotivoCierreSesion;
		this.motivo = motivo;
		this.vigente = vigente;
		this.esLunch = esLunch;
		this.esSalidaDefinitiva = esSalidaDefinitiva;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_motivo_cierre_sesion", unique = true, nullable = false)
	public int getIdMotivoCierreSesion() {
		return this.idMotivoCierreSesion;
	}

	public void setIdMotivoCierreSesion(int idMotivoCierreSesion) {
		this.idMotivoCierreSesion = idMotivoCierreSesion;
	}

	@Column(name = "motivo", nullable = false, length = 100)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "vigente", nullable = false)
	public boolean isVigente() {
		return this.vigente;
	}

	public void setVigente(boolean vigente) {
		this.vigente = vigente;
	}

	@Column(name = "es_lunch", nullable = false)
	public boolean isEsLunch() {
		return this.esLunch;
	}

	public void setEsLunch(boolean esLunch) {
		this.esLunch = esLunch;
	}

	@Column(name = "es_salida_definitiva", nullable = false)
	public boolean isEsSalidaDefinitiva() {
		return this.esSalidaDefinitiva;
	}

	public void setEsSalidaDefinitiva(boolean esSalidaDefinitiva) {
		this.esSalidaDefinitiva = esSalidaDefinitiva;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
