// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NivelEstructuraOrg generated by hbm2java
 */
@Entity
@Table(name = "nivel_estructura_org", schema = "seguridad", catalog = "siisspolweb")
public class NivelEstructuraOrg implements java.io.Serializable {

	private int idNivelEstructuraOrg;
	private short largoCodigo;
	private String descripcion;
	private int icono;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<EstructuraOrganizacional> estructuraOrganizacionals = new HashSet<EstructuraOrganizacional>(0);

	public NivelEstructuraOrg() {
	}

	public NivelEstructuraOrg(int idNivelEstructuraOrg, short largoCodigo, String descripcion, int icono,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idNivelEstructuraOrg = idNivelEstructuraOrg;
		this.largoCodigo = largoCodigo;
		this.descripcion = descripcion;
		this.icono = icono;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public NivelEstructuraOrg(int idNivelEstructuraOrg, short largoCodigo, String descripcion, int icono,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<EstructuraOrganizacional> estructuraOrganizacionals) {
		this.idNivelEstructuraOrg = idNivelEstructuraOrg;
		this.largoCodigo = largoCodigo;
		this.descripcion = descripcion;
		this.icono = icono;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.estructuraOrganizacionals = estructuraOrganizacionals;
	}

	@Id

	@Column(name = "id_nivel_estructura_org", unique = true, nullable = false)
	public int getIdNivelEstructuraOrg() {
		return this.idNivelEstructuraOrg;
	}

	public void setIdNivelEstructuraOrg(int idNivelEstructuraOrg) {
		this.idNivelEstructuraOrg = idNivelEstructuraOrg;
	}

	@Column(name = "largo_codigo", nullable = false)
	public short getLargoCodigo() {
		return this.largoCodigo;
	}

	public void setLargoCodigo(short largoCodigo) {
		this.largoCodigo = largoCodigo;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "icono", nullable = false)
	public int getIcono() {
		return this.icono;
	}

	public void setIcono(int icono) {
		this.icono = icono;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstructuraOrg")
	public Set<EstructuraOrganizacional> getEstructuraOrganizacionals() {
		return this.estructuraOrganizacionals;
	}

	public void setEstructuraOrganizacionals(Set<EstructuraOrganizacional> estructuraOrganizacionals) {
		this.estructuraOrganizacionals = estructuraOrganizacionals;
	}

}
