// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjetoValidaId generated by hbm2java
 */
@Embeddable
public class ObjetoValidaId implements java.io.Serializable {

	private String obj;
	private String col;

	public ObjetoValidaId() {
	}

	public ObjetoValidaId(String obj, String col) {
		this.obj = obj;
		this.col = col;
	}

	@Column(name = "obj", nullable = false)
	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	@Column(name = "col", nullable = false, length = 50)
	public String getCol() {
		return this.col;
	}

	public void setCol(String col) {
		this.col = col;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjetoValidaId))
			return false;
		ObjetoValidaId castOther = (ObjetoValidaId) other;

		return ((this.getObj() == castOther.getObj())
				|| (this.getObj() != null && castOther.getObj() != null && this.getObj().equals(castOther.getObj())))
				&& ((this.getCol() == castOther.getCol()) || (this.getCol() != null && castOther.getCol() != null
						&& this.getCol().equals(castOther.getCol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getObj() == null ? 0 : this.getObj().hashCode());
		result = 37 * result + (getCol() == null ? 0 : this.getCol().hashCode());
		return result;
	}

}
