// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Oficina generated by hbm2java
 */
@Entity
@Table(name = "oficina", schema = "seguridad", catalog = "siisspolweb", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_3"))
public class Oficina implements java.io.Serializable {

	private int idOficina;
	private Canton canton;
	private Empresa empresa;
	private Estado estado;
	private Provincia provincia;
	private Sucursal sucursal;
	private TipoOficina tipoOficina;
	private Usuario usuario;
	private String nombre;
	private String codigo;
	private String direccion;
	private String telefono;
	private String codigo2;
	private String telCodigoArea;
	private String telCodigoRegion;
	private String otroTelefono;
	private String codigo3;
	private Double latitud;
	private Double longitud;
	private String codigoRepOrg;
	private String codigoSep;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<UsuarioOficina> usuarioOficinas = new HashSet<UsuarioOficina>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Oficina() {
	}

	public Oficina(int idOficina, Canton canton, Empresa empresa, Estado estado, Provincia provincia, Sucursal sucursal,
			TipoOficina tipoOficina, String nombre, String codigo2, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idOficina = idOficina;
		this.canton = canton;
		this.empresa = empresa;
		this.estado = estado;
		this.provincia = provincia;
		this.sucursal = sucursal;
		this.tipoOficina = tipoOficina;
		this.nombre = nombre;
		this.codigo2 = codigo2;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Oficina(int idOficina, Canton canton, Empresa empresa, Estado estado, Provincia provincia, Sucursal sucursal,
			TipoOficina tipoOficina, Usuario usuario, String nombre, String codigo, String direccion, String telefono,
			String codigo2, String telCodigoArea, String telCodigoRegion, String otroTelefono, String codigo3,
			Double latitud, Double longitud, String codigoRepOrg, String codigoSep, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo, Set<UsuarioOficina> usuarioOficinas, Set<Usuario> usuarios) {
		this.idOficina = idOficina;
		this.canton = canton;
		this.empresa = empresa;
		this.estado = estado;
		this.provincia = provincia;
		this.sucursal = sucursal;
		this.tipoOficina = tipoOficina;
		this.usuario = usuario;
		this.nombre = nombre;
		this.codigo = codigo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.codigo2 = codigo2;
		this.telCodigoArea = telCodigoArea;
		this.telCodigoRegion = telCodigoRegion;
		this.otroTelefono = otroTelefono;
		this.codigo3 = codigo3;
		this.latitud = latitud;
		this.longitud = longitud;
		this.codigoRepOrg = codigoRepOrg;
		this.codigoSep = codigoSep;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.usuarioOficinas = usuarioOficinas;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "id_oficina", unique = true, nullable = false)
	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_canton", nullable = false)
	public Canton getCanton() {
		return this.canton;
	}

	public void setCanton(Canton canton) {
		this.canton = canton;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provincia", nullable = false)
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sucursal", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_oficina", nullable = false)
	public TipoOficina getTipoOficina() {
		return this.tipoOficina;
	}

	public void setTipoOficina(TipoOficina tipoOficina) {
		this.tipoOficina = tipoOficina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_supervisor")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo", length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "direccion", length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "codigo_2", nullable = false, length = 5)
	public String getCodigo2() {
		return this.codigo2;
	}

	public void setCodigo2(String codigo2) {
		this.codigo2 = codigo2;
	}

	@Column(name = "tel_codigo_area", length = 3)
	public String getTelCodigoArea() {
		return this.telCodigoArea;
	}

	public void setTelCodigoArea(String telCodigoArea) {
		this.telCodigoArea = telCodigoArea;
	}

	@Column(name = "tel_codigo_region", length = 3)
	public String getTelCodigoRegion() {
		return this.telCodigoRegion;
	}

	public void setTelCodigoRegion(String telCodigoRegion) {
		this.telCodigoRegion = telCodigoRegion;
	}

	@Column(name = "otro_telefono", length = 100)
	public String getOtroTelefono() {
		return this.otroTelefono;
	}

	public void setOtroTelefono(String otroTelefono) {
		this.otroTelefono = otroTelefono;
	}

	@Column(name = "codigo_3", unique = true, length = 20)
	public String getCodigo3() {
		return this.codigo3;
	}

	public void setCodigo3(String codigo3) {
		this.codigo3 = codigo3;
	}

	@Column(name = "latitud", precision = 53, scale = 0)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 53, scale = 0)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "codigo_rep_org", length = 4)
	public String getCodigoRepOrg() {
		return this.codigoRepOrg;
	}

	public void setCodigoRepOrg(String codigoRepOrg) {
		this.codigoRepOrg = codigoRepOrg;
	}

	@Column(name = "codigo_sep", length = 6)
	public String getCodigoSep() {
		return this.codigoSep;
	}

	public void setCodigoSep(String codigoSep) {
		this.codigoSep = codigoSep;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oficina")
	public Set<UsuarioOficina> getUsuarioOficinas() {
		return this.usuarioOficinas;
	}

	public void setUsuarioOficinas(Set<UsuarioOficina> usuarioOficinas) {
		this.usuarioOficinas = usuarioOficinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oficina")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
