// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UbicacionGeografica generated by hbm2java
 */
@Entity
@Table(name = "ubicacion_geografica", schema = "comun", catalog = "siisspolweb")
public class UbicacionGeografica implements java.io.Serializable {

	private int idUbicacionGeografica;
	private TipoUbicacionGeografica tipoUbicacionGeografica;
	private UbicacionGeografica ubicacionGeografica;
	private String descripcion;
	private String codigoUbicacion;
	private String codigoPostal;
	private boolean esOtro;
	private boolean visible;
	private boolean esCapital;
	private String codigo2;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<UbicacionGeografica> ubicacionGeograficas = new HashSet<UbicacionGeografica>(0);

	public UbicacionGeografica() {
	}

	public UbicacionGeografica(int idUbicacionGeografica, TipoUbicacionGeografica tipoUbicacionGeografica,
			String descripcion, String codigoUbicacion, boolean esOtro, boolean visible, boolean esCapital,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.tipoUbicacionGeografica = tipoUbicacionGeografica;
		this.descripcion = descripcion;
		this.codigoUbicacion = codigoUbicacion;
		this.esOtro = esOtro;
		this.visible = visible;
		this.esCapital = esCapital;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public UbicacionGeografica(int idUbicacionGeografica, TipoUbicacionGeografica tipoUbicacionGeografica,
			UbicacionGeografica ubicacionGeografica, String descripcion, String codigoUbicacion, String codigoPostal,
			boolean esOtro, boolean visible, boolean esCapital, String codigo2, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo, Set<UbicacionGeografica> ubicacionGeograficas) {
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.tipoUbicacionGeografica = tipoUbicacionGeografica;
		this.ubicacionGeografica = ubicacionGeografica;
		this.descripcion = descripcion;
		this.codigoUbicacion = codigoUbicacion;
		this.codigoPostal = codigoPostal;
		this.esOtro = esOtro;
		this.visible = visible;
		this.esCapital = esCapital;
		this.codigo2 = codigo2;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.ubicacionGeograficas = ubicacionGeograficas;
	}

	@Id

	@Column(name = "id_ubicacion_geografica", unique = true, nullable = false)
	public int getIdUbicacionGeografica() {
		return this.idUbicacionGeografica;
	}

	public void setIdUbicacionGeografica(int idUbicacionGeografica) {
		this.idUbicacionGeografica = idUbicacionGeografica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_ubicacion_geografica", nullable = false)
	public TipoUbicacionGeografica getTipoUbicacionGeografica() {
		return this.tipoUbicacionGeografica;
	}

	public void setTipoUbicacionGeografica(TipoUbicacionGeografica tipoUbicacionGeografica) {
		this.tipoUbicacionGeografica = tipoUbicacionGeografica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_padre")
	public UbicacionGeografica getUbicacionGeografica() {
		return this.ubicacionGeografica;
	}

	public void setUbicacionGeografica(UbicacionGeografica ubicacionGeografica) {
		this.ubicacionGeografica = ubicacionGeografica;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "codigo_ubicacion", nullable = false, length = 10)
	public String getCodigoUbicacion() {
		return this.codigoUbicacion;
	}

	public void setCodigoUbicacion(String codigoUbicacion) {
		this.codigoUbicacion = codigoUbicacion;
	}

	@Column(name = "codigo_postal", length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "es_otro", nullable = false)
	public boolean isEsOtro() {
		return this.esOtro;
	}

	public void setEsOtro(boolean esOtro) {
		this.esOtro = esOtro;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	@Column(name = "es_capital", nullable = false)
	public boolean isEsCapital() {
		return this.esCapital;
	}

	public void setEsCapital(boolean esCapital) {
		this.esCapital = esCapital;
	}

	@Column(name = "codigo_2", length = 5)
	public String getCodigo2() {
		return this.codigo2;
	}

	public void setCodigo2(String codigo2) {
		this.codigo2 = codigo2;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacionGeografica")
	public Set<UbicacionGeografica> getUbicacionGeograficas() {
		return this.ubicacionGeograficas;
	}

	public void setUbicacionGeograficas(Set<UbicacionGeografica> ubicacionGeograficas) {
		this.ubicacionGeograficas = ubicacionGeograficas;
	}

}
