// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "seguridad", catalog = "siisspolweb", uniqueConstraints = @UniqueConstraint(columnNames = "usuario_secuencial"))
public class Usuario implements java.io.Serializable {

	private String idUsuario;
	private EstadoUsuario estadoUsuario;
	private EstructuraOrganizacional estructuraOrganizacional;
	private Horario horario;
	private Oficina oficina;
	private Usuario usuario;
	private String nombre;
	private String email;
	private byte[] clave;
	private Date fechaUltimoCambioPwd;
	private boolean cambiarPwdProximoLogon;
	private boolean noPuedeCambiarPwd;
	private boolean pwdNuncaExpira;
	private boolean bloqueada;
	private int usuarioSecuencial;
	private String identificacion;
	private boolean cualquierEstacion;
	private int tiempoInactividad;
	private int idDashboardInicio;
	private byte[] foto;
	private String cargo;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<UsuarioOficina> usuarioOficinas = new HashSet<UsuarioOficina>(0);
	private Set<EstacionUsuario> estacionUsuarios = new HashSet<EstacionUsuario>(0);
	private Set<UsuarioCambio> usuarioCambios = new HashSet<UsuarioCambio>(0);
	private Set<GrupoUsuario> grupoUsuarios = new HashSet<GrupoUsuario>(0);
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<HistClave> histClaves = new HashSet<HistClave>(0);
	private Set<Oficina> oficinas = new HashSet<Oficina>(0);
	private Set<OpcionUso> opcionUsos = new HashSet<OpcionUso>(0);
	private Set<Permiso> permisos = new HashSet<Permiso>(0);
	private Set<UsuarioUbicacionGeografica> usuarioUbicacionGeograficas = new HashSet<UsuarioUbicacionGeografica>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Usuario() {
	}

	public Usuario(String idUsuario, EstadoUsuario estadoUsuario, Horario horario, String nombre,
			boolean cambiarPwdProximoLogon, boolean noPuedeCambiarPwd, boolean pwdNuncaExpira, boolean bloqueada,
			int usuarioSecuencial, boolean cualquierEstacion, int tiempoInactividad, int idDashboardInicio,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idUsuario = idUsuario;
		this.estadoUsuario = estadoUsuario;
		this.horario = horario;
		this.nombre = nombre;
		this.cambiarPwdProximoLogon = cambiarPwdProximoLogon;
		this.noPuedeCambiarPwd = noPuedeCambiarPwd;
		this.pwdNuncaExpira = pwdNuncaExpira;
		this.bloqueada = bloqueada;
		this.usuarioSecuencial = usuarioSecuencial;
		this.cualquierEstacion = cualquierEstacion;
		this.tiempoInactividad = tiempoInactividad;
		this.idDashboardInicio = idDashboardInicio;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Usuario(String idUsuario, EstadoUsuario estadoUsuario, EstructuraOrganizacional estructuraOrganizacional,
			Horario horario, Oficina oficina, Usuario usuario, String nombre, String email, byte[] clave,
			Date fechaUltimoCambioPwd, boolean cambiarPwdProximoLogon, boolean noPuedeCambiarPwd,
			boolean pwdNuncaExpira, boolean bloqueada, int usuarioSecuencial, String identificacion,
			boolean cualquierEstacion, int tiempoInactividad, int idDashboardInicio, byte[] foto, String cargo,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<UsuarioOficina> usuarioOficinas,
			Set<EstacionUsuario> estacionUsuarios, Set<UsuarioCambio> usuarioCambios, Set<GrupoUsuario> grupoUsuarios,
			Set<Favorito> favoritos, Set<HistClave> histClaves, Set<Oficina> oficinas, Set<OpcionUso> opcionUsos,
			Set<Permiso> permisos, Set<UsuarioUbicacionGeografica> usuarioUbicacionGeograficas, Set<Usuario> usuarios) {
		this.idUsuario = idUsuario;
		this.estadoUsuario = estadoUsuario;
		this.estructuraOrganizacional = estructuraOrganizacional;
		this.horario = horario;
		this.oficina = oficina;
		this.usuario = usuario;
		this.nombre = nombre;
		this.email = email;
		this.clave = clave;
		this.fechaUltimoCambioPwd = fechaUltimoCambioPwd;
		this.cambiarPwdProximoLogon = cambiarPwdProximoLogon;
		this.noPuedeCambiarPwd = noPuedeCambiarPwd;
		this.pwdNuncaExpira = pwdNuncaExpira;
		this.bloqueada = bloqueada;
		this.usuarioSecuencial = usuarioSecuencial;
		this.identificacion = identificacion;
		this.cualquierEstacion = cualquierEstacion;
		this.tiempoInactividad = tiempoInactividad;
		this.idDashboardInicio = idDashboardInicio;
		this.foto = foto;
		this.cargo = cargo;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.usuarioOficinas = usuarioOficinas;
		this.estacionUsuarios = estacionUsuarios;
		this.usuarioCambios = usuarioCambios;
		this.grupoUsuarios = grupoUsuarios;
		this.favoritos = favoritos;
		this.histClaves = histClaves;
		this.oficinas = oficinas;
		this.opcionUsos = opcionUsos;
		this.permisos = permisos;
		this.usuarioUbicacionGeograficas = usuarioUbicacionGeograficas;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "id_usuario", unique = true, nullable = false, length = 20)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public EstadoUsuario getEstadoUsuario() {
		return this.estadoUsuario;
	}

	public void setEstadoUsuario(EstadoUsuario estadoUsuario) {
		this.estadoUsuario = estadoUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estructura_organizacional")
	public EstructuraOrganizacional getEstructuraOrganizacional() {
		return this.estructuraOrganizacional;
	}

	public void setEstructuraOrganizacional(EstructuraOrganizacional estructuraOrganizacional) {
		this.estructuraOrganizacional = estructuraOrganizacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horario", nullable = false)
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oficina")
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_padre")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "clave")
	public byte[] getClave() {
		return this.clave;
	}

	public void setClave(byte[] clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ultimo_cambio_pwd", length = 23)
	public Date getFechaUltimoCambioPwd() {
		return this.fechaUltimoCambioPwd;
	}

	public void setFechaUltimoCambioPwd(Date fechaUltimoCambioPwd) {
		this.fechaUltimoCambioPwd = fechaUltimoCambioPwd;
	}

	@Column(name = "cambiar_pwd_proximo_logon", nullable = false)
	public boolean isCambiarPwdProximoLogon() {
		return this.cambiarPwdProximoLogon;
	}

	public void setCambiarPwdProximoLogon(boolean cambiarPwdProximoLogon) {
		this.cambiarPwdProximoLogon = cambiarPwdProximoLogon;
	}

	@Column(name = "no_puede_cambiar_pwd", nullable = false)
	public boolean isNoPuedeCambiarPwd() {
		return this.noPuedeCambiarPwd;
	}

	public void setNoPuedeCambiarPwd(boolean noPuedeCambiarPwd) {
		this.noPuedeCambiarPwd = noPuedeCambiarPwd;
	}

	@Column(name = "pwd_nunca_expira", nullable = false)
	public boolean isPwdNuncaExpira() {
		return this.pwdNuncaExpira;
	}

	public void setPwdNuncaExpira(boolean pwdNuncaExpira) {
		this.pwdNuncaExpira = pwdNuncaExpira;
	}

	@Column(name = "bloqueada", nullable = false)
	public boolean isBloqueada() {
		return this.bloqueada;
	}

	public void setBloqueada(boolean bloqueada) {
		this.bloqueada = bloqueada;
	}

	@Column(name = "usuario_secuencial", unique = true, nullable = false)
	public int getUsuarioSecuencial() {
		return this.usuarioSecuencial;
	}

	public void setUsuarioSecuencial(int usuarioSecuencial) {
		this.usuarioSecuencial = usuarioSecuencial;
	}

	@Column(name = "identificacion", length = 15)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "cualquier_estacion", nullable = false)
	public boolean isCualquierEstacion() {
		return this.cualquierEstacion;
	}

	public void setCualquierEstacion(boolean cualquierEstacion) {
		this.cualquierEstacion = cualquierEstacion;
	}

	@Column(name = "tiempo_inactividad", nullable = false)
	public int getTiempoInactividad() {
		return this.tiempoInactividad;
	}

	public void setTiempoInactividad(int tiempoInactividad) {
		this.tiempoInactividad = tiempoInactividad;
	}

	@Column(name = "id_dashboard_inicio", nullable = false)
	public int getIdDashboardInicio() {
		return this.idDashboardInicio;
	}

	public void setIdDashboardInicio(int idDashboardInicio) {
		this.idDashboardInicio = idDashboardInicio;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Column(name = "cargo", length = 2)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioOficina> getUsuarioOficinas() {
		return this.usuarioOficinas;
	}

	public void setUsuarioOficinas(Set<UsuarioOficina> usuarioOficinas) {
		this.usuarioOficinas = usuarioOficinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<EstacionUsuario> getEstacionUsuarios() {
		return this.estacionUsuarios;
	}

	public void setEstacionUsuarios(Set<EstacionUsuario> estacionUsuarios) {
		this.estacionUsuarios = estacionUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioCambio> getUsuarioCambios() {
		return this.usuarioCambios;
	}

	public void setUsuarioCambios(Set<UsuarioCambio> usuarioCambios) {
		this.usuarioCambios = usuarioCambios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<GrupoUsuario> getGrupoUsuarios() {
		return this.grupoUsuarios;
	}

	public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
		this.grupoUsuarios = grupoUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<HistClave> getHistClaves() {
		return this.histClaves;
	}

	public void setHistClaves(Set<HistClave> histClaves) {
		this.histClaves = histClaves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Oficina> getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set<Oficina> oficinas) {
		this.oficinas = oficinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<OpcionUso> getOpcionUsos() {
		return this.opcionUsos;
	}

	public void setOpcionUsos(Set<OpcionUso> opcionUsos) {
		this.opcionUsos = opcionUsos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioUbicacionGeografica> getUsuarioUbicacionGeograficas() {
		return this.usuarioUbicacionGeograficas;
	}

	public void setUsuarioUbicacionGeograficas(Set<UsuarioUbicacionGeografica> usuarioUbicacionGeograficas) {
		this.usuarioUbicacionGeograficas = usuarioUbicacionGeograficas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
