// default package
// Generated 30-mar-2017 11:07:53 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioOficinaId generated by hbm2java
 */
@Embeddable
public class UsuarioOficinaId implements java.io.Serializable {

	private String idUsuario;
	private int idOficina;

	public UsuarioOficinaId() {
	}

	public UsuarioOficinaId(String idUsuario, int idOficina) {
		this.idUsuario = idUsuario;
		this.idOficina = idOficina;
	}

	@Column(name = "id_usuario", nullable = false, length = 20)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_oficina", nullable = false)
	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioOficinaId))
			return false;
		UsuarioOficinaId castOther = (UsuarioOficinaId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
				&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())))
				&& (this.getIdOficina() == castOther.getIdOficina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result + this.getIdOficina();
		return result;
	}

}
